import type {
  EvidenceLevel,
  EvidenceRef,
  KnowledgeDomain,
  RiskLevel,
  SeedCandidate,
  SeedContentCategory,
  SeedReview,
} from '../domain';

const REVIEW_FROZEN_AT = '2026-08-23T18:00:00.000Z';

interface EvidenceInput {
  readonly sourceId: string;
  readonly title: string;
  readonly publisher: string;
  readonly url: string;
  readonly publishedAt: string;
  readonly level: EvidenceLevel;
  readonly language?: 'zh' | 'en';
  readonly dateBasis?: EvidenceRef['dateBasis'];
}

interface CandidateInput {
  readonly id: string;
  readonly slug: string;
  readonly seedCategory: SeedContentCategory;
  readonly title: string;
  readonly originalTitle?: string;
  readonly summary: string;
  readonly kind: SeedCandidate['kind'];
  readonly domains: readonly KnowledgeDomain[];
  readonly topicSlugs: readonly string[];
  readonly tags: readonly string[];
  readonly toolIds: readonly string[];
  readonly audience?: SeedCandidate['audience'];
  readonly publishedAt: string;
  readonly freshness: SeedCandidate['freshness'];
  readonly whyItMatters: string;
  readonly salesImplication: string;
  readonly roleOrgImplication: string;
  readonly nextAction: string;
  readonly evidence: readonly EvidenceInput[];
  readonly riskLevel: RiskLevel;
  readonly changeWindow: SeedReview['changeWindow'];
  readonly factType: SeedReview['factType'];
  readonly verificationNotes: string;
}

function defineCandidate(input: CandidateInput): SeedCandidate {
  return {
    id: input.id,
    slug: input.slug,
    seedCategory: input.seedCategory,
    title: { zh: input.title },
    originalTitle: input.originalTitle,
    summary: { zh: input.summary },
    kind: input.kind,
    domains: input.domains,
    topicSlugs: input.topicSlugs,
    tags: input.tags,
    toolIds: input.toolIds,
    audience: input.audience ?? ['transitioning_seller', 'ai_ae', 'solution'],
    publishedAt: input.publishedAt,
    updatedAt: REVIEW_FROZEN_AT,
    freshness: input.freshness,
    whyItMatters: { zh: input.whyItMatters },
    salesImplication: { zh: input.salesImplication },
    roleOrgImplication: { zh: input.roleOrgImplication },
    nextAction: { zh: input.nextAction },
    evidence: input.evidence.map((item, index) => ({
      id: `${input.id}-e${index + 1}`,
      sourceId: item.sourceId,
      title: item.title,
      publisher: item.publisher,
      url: item.url,
      publishedAt: item.publishedAt,
      level: item.level,
      language: item.language ?? 'en',
      allowlisted: true,
      dateBasis: item.dateBasis ?? 'published',
    })),
    relatedItemIds: [],
    editorialStatus: 'candidate',
    riskLevel: input.riskLevel,
    publicationMode: 'manual',
    seedContent: true,
    audit: {
      sourceFingerprint: `source-ref:${input.slug}:2026-08-23`,
      ruleVersion: 'saas-602-seed-review-v1',
      processedAt: REVIEW_FROZEN_AT,
      releaseVersion: 'seed-review-2026-08-23',
      rollbackState: 'available',
    },
    review: {
      status: 'pending_owner_review',
      verifiedAt: REVIEW_FROZEN_AT,
      changeWindow: input.changeWindow,
      factType: input.factType,
      verificationNotes: input.verificationNotes,
    },
  };
}

export const seedCandidates = [
  defineCandidate({
    id: 'ST-001', slug: 'frontier-model-price-performance', seedCategory: 'ai_technology',
    title: '前沿模型的价格性能比正在改变企业选型',
    originalTitle: 'Advancing the price-performance frontier with GPT-5.6',
    summary: 'OpenAI 于 7 月 30 日宣布下调 GPT-5.6 Luna 与 Terra 的价格，并把更低单位成本作为企业规模化工作流的产品主张。',
    kind: 'update', domains: ['ai_technology', 'enterprise_sales'],
    topicSlugs: ['agent-business-model', 'ai-poc-scale'], tags: ['模型成本', '选型', '规模化'],
    toolIds: ['value-hypothesis-one-pager', 'poc-success-canvas'], publishedAt: '2026-07-30T10:00:00.000Z', freshness: 'current',
    whyItMatters: '价格变化会影响单位任务成本和原先的 ROI 假设，但厂商降价不等于客户已经获得价值。',
    salesImplication: '报价讨论应从单次 Token 价格扩展到任务完成率、人工复核、失败重试和容量保障。',
    roleOrgImplication: '销售与解决方案岗位需要能够解释成本结构，并把易变价格与长期价值证据分开。',
    nextAction: '用价值假设一页纸重算一个虚构工作流的单位任务总成本，并写明价格再次变化时的敏感项。',
    evidence: [{ sourceId: 'openai-news-rss', title: 'Advancing the price-performance frontier with GPT-5.6', publisher: 'OpenAI', url: 'https://openai.com/index/advancing-the-price-performance-frontier-with-gpt-5-6', publishedAt: '2026-07-30T10:00:00.000Z', level: 'official' }],
    riskLevel: 'high', changeWindow: 'within_30_days', factType: 'company_claim',
    verificationNotes: '标题、日期与摘要由 OpenAI 官方 RSS 实时核验；未引用或推断具体价格，发布前仍需重新核价。',
  }),
  defineCandidate({
    id: 'ST-002', slug: 'ultrafast-inference-service-tier', seedCategory: 'ai_technology',
    title: '推理速度开始成为可单独采购的服务层',
    originalTitle: 'Previewing Ultrafast mode: GPT-5.6 Sol at up to 14X the speed',
    summary: 'OpenAI 于 8 月 13 日预览 Ultrafast 服务层，并称 GPT-5.6 Sol 的输出速度最高可达原服务的 14 倍、每秒 750 个输出 Token。',
    kind: 'update', domains: ['ai_technology', 'enterprise_sales'], topicSlugs: ['agent-business-model'],
    tags: ['推理速度', '服务等级', '延迟'], toolIds: ['value-hypothesis-one-pager'], publishedAt: '2026-08-13T10:00:00.000Z', freshness: 'breaking',
    whyItMatters: '对实时客服、语音和代理流程，延迟可以直接改变用户体验和流程可行性。',
    salesImplication: '不能只展示最快速度；应明确典型负载、峰值、地区、稳定性和价格的共同验收方式。',
    roleOrgImplication: 'AI 商业岗位需要把技术基准翻译成业务场景 SLA，并清楚标识厂商性能主张。',
    nextAction: '选一个实时场景，写出用户可感知延迟、吞吐、失败率和成本四项验收线。',
    evidence: [{ sourceId: 'openai-news-rss', title: 'Previewing Ultrafast mode: GPT-5.6 Sol at up to 14X the speed', publisher: 'OpenAI', url: 'https://openai.com/index/previewing-ultrafast', publishedAt: '2026-08-13T10:00:00.000Z', level: 'official' }],
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'company_claim',
    verificationNotes: '性能数字是 OpenAI 官方产品主张，未作为第三方独立测评结论。',
  }),
  defineCandidate({
    id: 'ST-003', slug: 'zero-data-retention-frontier-models', seedCategory: 'ai_technology',
    title: '前沿模型开始提供更细的数据保留控制',
    originalTitle: 'Offering Zero Data Retention for frontier models',
    summary: 'OpenAI 于 8 月 19 日重申符合条件的 API 客户可使用 Zero Data Retention，并预告 Private Safety Processing。',
    kind: 'update', domains: ['ai_technology', 'enterprise_sales', 'role_org'], topicSlugs: ['ai-trust-governance', 'ai-buying-committee'],
    tags: ['数据保留', '隐私', '企业采购'], toolIds: ['discovery-interview', 'stakeholder-adoption-risk'], publishedAt: '2026-08-19T19:00:00.000Z', freshness: 'breaking',
    whyItMatters: '数据如何保留和用于安全处理，往往是企业采购能否推进的前置条件。',
    salesImplication: '销售应要求产品、安全和法务共同确认资格、例外、日志与合同，而不是只复述“零保留”。',
    roleOrgImplication: '解决方案与客户成功岗位需要持续维护数据流、责任边界和客户可验证证据。',
    nextAction: '把“数据是否保留”拆成采集、传输、推理、日志、安全检测和删除六个问题。',
    evidence: [{ sourceId: 'openai-news-rss', title: 'Offering Zero Data Retention for frontier models', publisher: 'OpenAI', url: 'https://openai.com/index/offering-zero-data-retention-for-frontier-models', publishedAt: '2026-08-19T19:00:00.000Z', level: 'official' }],
    riskLevel: 'high', changeWindow: 'within_30_days', factType: 'company_claim',
    verificationNotes: '仅陈述 OpenAI 已公开的产品政策主张；具体资格、例外和合同条件须客户自行核验。',
  }),
  defineCandidate({
    id: 'ST-004', slug: 'contract-first-agent-delegation', seedCategory: 'ai_technology',
    title: '多代理协作要先把工作拆成可验证契约',
    originalTitle: 'How agents can delegate better',
    summary: 'Google Cloud 8 月 21 日总结其与 DeepMind 相关研究，提出可验证分解、成本匹配、最小数据权限和必要的人类判断。',
    kind: 'explainer', domains: ['ai_technology', 'enterprise_sales', 'role_org'], topicSlugs: ['agent-business-model', 'ai-trust-governance'],
    tags: ['多代理', '委派', '可验证性'], toolIds: ['poc-success-canvas', 'stakeholder-adoption-risk'], publishedAt: '2026-08-21T00:00:00.000Z', freshness: 'breaking',
    whyItMatters: '代理能否执行复杂流程，取决于任务是否可验收、权限是否受限，而不只是模型能力。',
    salesImplication: '演示应展示任务合同、失败处理和人工升级点，避免把“自动完成”当成不可审计黑箱。',
    roleOrgImplication: '管理者需要决定哪些结果可自动验收、哪些必须由专家判断，并防止委派链扩大权限。',
    nextAction: '选一个三步流程，为每一步写输入、输出、权限、验收人和失败升级条件。',
    evidence: [{ sourceId: 'google-cloud-ai-blog', title: 'How agents can delegate better', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/ai-machine-learning/how-agents-can-delegate-better', publishedAt: '2026-08-21T00:00:00.000Z', level: 'official' }],
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'company_claim',
    verificationNotes: '页面日期与四项原则已实时打开核验；其组织建议属于 Google 的研究解读。',
  }),
  defineCandidate({
    id: 'ST-005', slug: 'build-time-agents-deterministic-production', seedCategory: 'ai_technology',
    title: '代理可以在开发期工作，生产只运行确定性产物',
    originalTitle: 'Agentic Data Operations Platform (ADOP): Data engineering into hours',
    summary: 'AWS 8 月 21 日发布 ADOP 参考架构：代理在开发环境生成数据管道、质量和治理产物，经人工与 CI/CD 审核后由生产运行确定性代码。',
    kind: 'case', domains: ['ai_technology', 'role_org', 'enterprise_sales'], topicSlugs: ['ai-poc-scale', 'workflow-adoption', 'ai-trust-governance'],
    tags: ['确定性产物', 'AgentOps', '治理'], toolIds: ['ai-maturity-scan', 'poc-success-canvas'], publishedAt: '2026-08-21T17:06:17.000Z', freshness: 'breaking',
    whyItMatters: '它展示了“使用 AI 构建”与“让 AI 在生产持续决策”之间可以有更低风险的架构选择。',
    salesImplication: '面对监管或审计敏感客户，可先讨论生成后审核的静态产物，而非强推运行时自主代理。',
    roleOrgImplication: '工程、治理与业务团队需要共同维护架构合同、审核门和升级路径。',
    nextAction: '把一个代理方案分成开发期生成、人工审核、生产执行三层，并标出每层的数据和权限。',
    evidence: [{ sourceId: 'aws-ai-blog-rss', title: 'Agentic Data Operations Platform (ADOP): Data engineering into hours', publisher: 'Amazon Web Services', url: 'https://aws.amazon.com/blogs/machine-learning/agentic-data-operations-platform-adop-data-engineering-into-hours/', publishedAt: '2026-08-21T17:06:17.000Z', level: 'official' }],
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'company_claim',
    verificationNotes: '架构与效益描述来自 AWS 官方作者；未把方向性效率描述改写为已独立验证结果。',
  }),
  defineCandidate({
    id: 'ST-006', slug: 'enterprise-agent-control-plane', seedCategory: 'ai_technology',
    title: '企业代理平台正在把身份、审计和治理做成控制面',
    originalTitle: 'The new Gemini Enterprise: one platform for agent development, orchestration, and governance',
    summary: 'Google Cloud 4 月 22 日发布新版 Gemini Enterprise，称其 Agent Platform 提供代理身份、网关、模拟、可观测性与统一治理能力。',
    kind: 'update', domains: ['ai_technology', 'role_org', 'enterprise_sales'], topicSlugs: ['agent-business-model', 'ai-trust-governance'],
    tags: ['代理平台', '身份', '审计'], toolIds: ['ai-maturity-scan', 'stakeholder-adoption-risk'], publishedAt: '2026-04-22T00:00:00.000Z', freshness: 'current',
    whyItMatters: '当企业从几个试验代理扩展到大量代理时，身份、权限和生命周期会成为独立采购议题。',
    salesImplication: '价值表达应覆盖治理成本和代理蔓延风险，不能只展示单个代理的功能。',
    roleOrgImplication: 'IT 和安全会从审批某个工具转向管理代理实体、权限、活动和下线。',
    nextAction: '在成熟度扫描中增加代理数量、身份、权限、日志、测试和下线六项控制面问题。',
    evidence: [{ sourceId: 'google-cloud-ai-blog', title: 'The new Gemini Enterprise: one platform for agent development, orchestration, and governance', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/ai-machine-learning/the-new-gemini-enterprise-one-platform-for-agent-development', publishedAt: '2026-04-22T00:00:00.000Z', level: 'official' }],
    riskLevel: 'medium', changeWindow: 'evergreen', factType: 'company_claim',
    verificationNotes: '产品能力为 Google Cloud 官方自述，未验证各能力的可用地区、版本和实际效果。',
  }),
  defineCandidate({
    id: 'ST-007', slug: 'long-running-agent-model-tier', seedCategory: 'ai_technology',
    title: '长时间运行的代理成为高端模型的新卖点',
    originalTitle: 'Introducing Claude Opus 5',
    summary: 'Anthropic 7 月 24 日发布 Claude Opus 5，并把长时间运行的代理、编码与专业工作改进作为该层级的主要产品主张。',
    kind: 'update', domains: ['ai_technology', 'enterprise_sales'], topicSlugs: ['agent-business-model'],
    tags: ['长任务', '模型层级', '代理'], toolIds: ['poc-success-canvas'], publishedAt: '2026-07-24T00:00:00.000Z', freshness: 'current',
    whyItMatters: '模型从回答问题走向长任务执行后，成功标准需要覆盖中间状态、恢复和责任边界。',
    salesImplication: '销售应把“能运行更久”转成可验证的任务完成率、检查点、恢复成本和人工监督。',
    roleOrgImplication: '岗位能力会从提示词扩展到任务设计、状态管理、评估和异常处理。',
    nextAction: '为一个超过 30 分钟的代理任务定义三个检查点和两个必须转人工的异常。',
    evidence: [{ sourceId: 'anthropic-news', title: 'Introducing Claude Opus 5', publisher: 'Anthropic', url: 'https://www.anthropic.com/news/claude-opus-5', publishedAt: '2026-07-24T00:00:00.000Z', level: 'official' }],
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'company_claim',
    verificationNotes: '只保留新闻页公开的产品定位；性能提升未作为第三方评测事实。',
  }),
  defineCandidate({
    id: 'ST-008', slug: 'responsible-ai-reporting-gap', seedCategory: 'ai_technology',
    title: 'AI 能力报告快于责任与安全报告',
    originalTitle: 'The 2026 AI Index Report',
    summary: 'Stanford HAI 2026 AI Index 指出，领先模型开发者普遍报告能力基准，但责任 AI 基准披露仍不一致；报告记录的 AI 事件从 2024 年的 233 起增至 362 起。',
    kind: 'explainer', domains: ['ai_technology', 'role_org'], topicSlugs: ['ai-trust-governance'],
    tags: ['责任AI', '安全评估', '披露'], toolIds: ['stakeholder-adoption-risk'], publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'evergreen',
    whyItMatters: '采购方看到能力分数时，仍需要单独询问安全、偏差、透明度和事故证据。',
    salesImplication: '不要用能力榜单替代风险证据；应把未披露项放入验证清单。',
    roleOrgImplication: '产品、安全、法务和业务需要共同定义哪些责任指标阻塞上线。',
    nextAction: '挑一个候选方案，列出能力、可靠性、安全、透明度四类已知与未知证据。',
    evidence: [{ sourceId: 'stanford-ai-index-2026', title: 'The 2026 AI Index Report', publisher: 'Stanford HAI', url: 'https://hai.stanford.edu/ai-index/2026-ai-index-report', publishedAt: '2026-08-23T00:00:00.000Z', level: 'single_source', dateBasis: 'observed' }],
    riskLevel: 'medium', changeWindow: 'evergreen', factType: 'research_finding',
    verificationNotes: '指标从 Stanford HAI 官方报告页核验；保留其汇编研究属性，不推断因果。',
  }),
  defineCandidate({
    id: 'ST-009', slug: 'jagged-frontier-agent-reliability', seedCategory: 'ai_technology',
    title: '代理能力快速上升，但可靠性仍呈锯齿状',
    originalTitle: 'The 2026 AI Index Report',
    summary: 'Stanford HAI 2026 AI Index 报告称，代理在 OSWorld 基准的任务成功率由约 12% 提升到约 66%，但在结构化基准上仍约有三分之一任务失败。',
    kind: 'explainer', domains: ['ai_technology', 'enterprise_sales'], topicSlugs: ['ai-poc-scale', 'ai-trust-governance'],
    tags: ['可靠性', '评估', '代理'], toolIds: ['poc-success-canvas'], publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'evergreen',
    whyItMatters: '平均能力进步不能证明客户的具体任务已稳定可用。',
    salesImplication: 'POC 应使用客户任务集、失败类型和人工恢复成本，而不是只引用通用基准。',
    roleOrgImplication: '实施团队需要持续评估、观察失败并维护人工兜底。',
    nextAction: '为一个目标场景准备 20 个代表任务，预先定义成功、部分成功和失败。',
    evidence: [{ sourceId: 'stanford-ai-index-2026', title: 'The 2026 AI Index Report — Technical Performance', publisher: 'Stanford HAI', url: 'https://hai.stanford.edu/ai-index/2026-ai-index-report/technical-performance', publishedAt: '2026-08-23T00:00:00.000Z', level: 'single_source', dateBasis: 'observed' }],
    riskLevel: 'medium', changeWindow: 'evergreen', factType: 'research_finding',
    verificationNotes: '指标从 Stanford HAI 官方报告页核验；基准表现不外推为任意企业任务表现。',
  }),
  defineCandidate({
    id: 'ST-010', slug: 'prototype-to-production-ten-questions', seedCategory: 'ai_technology',
    title: 'AI 原型转生产要同时回答接入、规模与治理问题',
    originalTitle: '10 questions every startup should answer before moving to production with their AI prototype',
    summary: 'Google Cloud 8 月 20 日把原型转生产风险归为 Onboard、Scale、Govern 三组，覆盖身份、容量、成本、密钥和代理控制。',
    kind: 'method', domains: ['ai_technology', 'enterprise_sales', 'role_org'], topicSlugs: ['ai-poc-scale', 'ai-trust-governance'],
    tags: ['原型转生产', 'IAM', '容量'], toolIds: ['ai-maturity-scan', 'poc-success-canvas'], publishedAt: '2026-08-20T00:00:00.000Z', freshness: 'breaking',
    whyItMatters: '客户说“原型能用”时，生产身份、容量、账单和行为边界可能仍未建立。',
    salesImplication: '发现问题要覆盖谁拥有云项目、如何扩容、谁承担费用和谁能停止代理。',
    roleOrgImplication: '从原型到生产需要产品、工程、云管理员、安全和财务共同承担门槛。',
    nextAction: '用成熟度扫描逐项回答身份、容量、成本、密钥和代理边界；未知项标负责人。',
    evidence: [{ sourceId: 'google-cloud-ai-blog', title: '10 questions every startup should answer before moving to production with their AI prototype', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/topics/developers-practitioners/10-questions-for-your-startup-developers', publishedAt: '2026-08-20T00:00:00.000Z', level: 'official' }],
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'company_claim',
    verificationNotes: '页面日期、三组问题和主要控制项已实时核验；具体云产品建议仍是 Google 观点。',
  }),
  defineCandidate({
    id: 'ST-011', slug: 'production-readiness-discovery', seedCategory: 'enterprise_sales_method',
    title: '把原型转生产风险前置到销售发现',
    summary: '基于 Google Cloud 的十项问题，销售发现可在 POC 前识别身份、容量、成本、数据、密钥和代理权限是否有明确负责人。',
    kind: 'method', domains: ['enterprise_sales', 'ai_technology', 'role_org'], topicSlugs: ['ai-poc-scale', 'ai-buying-committee'],
    tags: ['销售发现', '生产就绪', '责任人'], toolIds: ['discovery-interview', 'ai-maturity-scan'], publishedAt: '2026-08-20T00:00:00.000Z', freshness: 'current',
    whyItMatters: '这些条件如果在演示成功后才出现，会让项目看似技术失败，实则是组织准备不足。',
    salesImplication: '发现访谈要同时问业务结果与生产约束，并把未知项转成共同验证计划。',
    roleOrgImplication: '销售不替代架构师或安全人员，但需要识别何时把他们拉入决策链。',
    nextAction: '从十项问题中选出最影响目标客户的五项，加入下一次发现访谈。',
    evidence: [{ sourceId: 'google-cloud-ai-blog', title: '10 questions every startup should answer before moving to production with their AI prototype', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/topics/developers-practitioners/10-questions-for-your-startup-developers', publishedAt: '2026-08-20T00:00:00.000Z', level: 'official' }],
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '问题框架来自官方文章；将其前置到销售发现是编辑方法推断。',
  }),
  defineCandidate({
    id: 'ST-012', slug: 'poc-four-layer-success-gates', seedCategory: 'enterprise_sales_method',
    title: 'AI POC 应同时设置业务、技术、风险和采用四层成功门',
    summary: 'AWS ADOP 的阶段与指标建议、Google 的生产就绪问题共同表明，只验证模型输出不足以决定是否规模化。',
    kind: 'method', domains: ['enterprise_sales', 'ai_technology', 'role_org'], topicSlugs: ['ai-poc-scale'],
    tags: ['POC', '成功标准', '采用'], toolIds: ['poc-success-canvas'], publishedAt: '2026-08-21T17:06:17.000Z', freshness: 'current',
    whyItMatters: '单一准确率可能掩盖业务价值、越权、使用阻力和运营成本。',
    salesImplication: '在 POC 启动前让不同验收人签认各自指标和停止条件。',
    roleOrgImplication: '业务、技术、安全与最终用户应分别拥有验收责任，而不是由供应商单方宣布成功。',
    nextAction: '用 POC 画布为一个虚构场景各写一项业务、技术、风险和采用指标。',
    evidence: [
      { sourceId: 'aws-ai-blog-rss', title: 'Agentic Data Operations Platform (ADOP): Data engineering into hours', publisher: 'Amazon Web Services', url: 'https://aws.amazon.com/blogs/machine-learning/agentic-data-operations-platform-adop-data-engineering-into-hours/', publishedAt: '2026-08-21T17:06:17.000Z', level: 'official' },
      { sourceId: 'google-cloud-ai-blog', title: '10 questions every startup should answer before moving to production with their AI prototype', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/topics/developers-practitioners/10-questions-for-your-startup-developers', publishedAt: '2026-08-20T00:00:00.000Z', level: 'official' },
    ],
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '四层成功门是对两份官方方法材料的编辑整合，不是两家厂商共同发布的标准。',
  }),
  defineCandidate({
    id: 'ST-013', slug: 'ai-buying-committee-accountability-map', seedCategory: 'enterprise_sales_method',
    title: 'AI 采购委员会要围绕责任而不是职位名称建图',
    summary: 'Google 的代理控制面和 NIST AI RMF 分别强调身份、审计、风险与组织责任，说明 AI 采购常同时涉及业务、IT、安全、法务和使用者。',
    kind: 'method', domains: ['enterprise_sales', 'role_org', 'ai_technology'], topicSlugs: ['ai-buying-committee', 'ai-trust-governance'],
    tags: ['采购委员会', '责任', '干系人'], toolIds: ['stakeholder-adoption-risk', 'discovery-interview'], publishedAt: '2026-04-22T00:00:00.000Z', freshness: 'evergreen',
    whyItMatters: '同一职位在不同客户可能拥有不同否决权，按责任建图更接近真实决策。',
    salesImplication: '区分业务价值、数据、身份、安全、合同、预算和采用七类责任及最终拍板人。',
    roleOrgImplication: '实施后这些责任仍需存在，不能把全部风险转给 IT 或供应商。',
    nextAction: '用干系人清单为一个虚构客户标出七类责任、证据和升级路径。',
    evidence: [
      { sourceId: 'google-cloud-ai-blog', title: 'The new Gemini Enterprise: one platform for agent development, orchestration, and governance', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/ai-machine-learning/the-new-gemini-enterprise-one-platform-for-agent-development', publishedAt: '2026-04-22T00:00:00.000Z', level: 'official' },
      { sourceId: 'nist-ai-rmf', title: 'AI Risk Management Framework', publisher: 'NIST', url: 'https://www.nist.gov/itl/ai-risk-management-framework', publishedAt: '2026-04-07T00:00:00.000Z', level: 'official', dateBasis: 'last_updated' },
    ],
    riskLevel: 'medium', changeWindow: 'evergreen', factType: 'editorial_inference',
    verificationNotes: '采购委员会结构是对治理责任的销售方法映射，不声称 NIST 指定了这些职位。',
  }),
  defineCandidate({
    id: 'ST-014', slug: 'ai-value-evidence-ladder', seedCategory: 'enterprise_sales_method',
    title: 'AI 价值证明要从厂商案例走到客户自己的行为证据',
    summary: 'OpenAI 8 月企业采用材料与 Microsoft 2026 工作趋势研究都强调从助手到执行、从个人使用到组织系统；两者均属于发布方自己的研究与案例。',
    kind: 'method', domains: ['enterprise_sales', 'role_org', 'ai_technology'], topicSlugs: ['agent-business-model', 'workflow-adoption'],
    tags: ['价值证明', '采用', '证据'], toolIds: ['value-hypothesis-one-pager', 'poc-success-canvas'], publishedAt: '2026-08-12T06:00:00.000Z', freshness: 'current',
    whyItMatters: '外部案例只能证明某种结果可能发生，不能替代目标客户的基线、行为和财务证据。',
    salesImplication: '按“厂商主张—外部研究—客户基线—试点行为—业务结果”逐级增强证据。',
    roleOrgImplication: '客户团队需要共同定义数据口径和复核责任，避免供应商单方面归因。',
    nextAction: '为一个价值主张列出五级证据，标记目前所在层级和下一步补证动作。',
    evidence: [
      { sourceId: 'openai-news-rss', title: 'From assistance to execution: How enterprises put AI to work', publisher: 'OpenAI', url: 'https://openai.com/index/how-enterprises-put-ai-to-work', publishedAt: '2026-08-12T06:00:00.000Z', level: 'official' },
      { sourceId: 'microsoft-worklab', title: '2026 Work Trend Index Annual Report', publisher: 'Microsoft WorkLab', url: 'https://www.microsoft.com/en-us/worklab/work-trend-index/agents-human-agency-and-the-opportunity-for-every-organization', publishedAt: '2026-05-05T00:00:00.000Z', level: 'single_source' },
    ],
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '两份发布者材料的归属已明确；证据阶梯为本站编辑方法。',
  }),
  defineCandidate({
    id: 'ST-015', slug: 'land-expand-with-governance-gate', seedCategory: 'enterprise_sales_method',
    title: '从小试点扩展前，要先通过治理控制面门',
    summary: 'Google Gemini Enterprise 把代理身份、网关、模拟与可观测性作为规模化能力，支持把治理准备度设置为扩展前置门。',
    kind: 'method', domains: ['enterprise_sales', 'ai_technology', 'role_org'], topicSlugs: ['ai-poc-scale', 'ai-trust-governance'],
    tags: ['Land and Expand', '治理门', '规模化'], toolIds: ['ai-maturity-scan', 'poc-success-canvas'], publishedAt: '2026-04-22T00:00:00.000Z', freshness: 'evergreen',
    whyItMatters: '一个部门的成功试用不代表身份、权限、审计和支持模式能承受全组织扩展。',
    salesImplication: '扩展方案应把控制面、运营责任和回退能力作为商业里程碑。',
    roleOrgImplication: 'IT 与安全要从一次性审批转向持续生命周期管理。',
    nextAction: '为试点扩展设置四项治理门：身份、权限、可观测性和下线。',
    evidence: [{ sourceId: 'google-cloud-ai-blog', title: 'The new Gemini Enterprise: one platform for agent development, orchestration, and governance', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/ai-machine-learning/the-new-gemini-enterprise-one-platform-for-agent-development', publishedAt: '2026-04-22T00:00:00.000Z', level: 'official' }],
    riskLevel: 'medium', changeWindow: 'evergreen', factType: 'editorial_inference',
    verificationNotes: '治理能力为 Google 产品自述；将其转为销售扩展门是编辑建议。',
  }),
  defineCandidate({
    id: 'ST-016', slug: 'discover-work-redesign-not-tool-usage', seedCategory: 'enterprise_sales_method',
    title: '发现访谈要问工作如何重构，而不只是工具会不会用',
    summary: 'Microsoft 2026 Work Trend Index 报告称，文化、经理支持和人才实践等组织因素，与受访者报告的 AI 影响关联度高于个人努力。',
    kind: 'method', domains: ['enterprise_sales', 'role_org'], topicSlugs: ['workflow-adoption'],
    tags: ['工作重构', '采用', '发现访谈'], toolIds: ['discovery-interview', 'stakeholder-adoption-risk'], publishedAt: '2026-05-05T00:00:00.000Z', freshness: 'evergreen',
    whyItMatters: '仅培训用户点击功能，无法解决指标、激励、经理示范和安全边界仍按旧方式运行的问题。',
    salesImplication: '发现应覆盖旧流程为什么存在、谁被考核、谁承担失败和谁有权改流程。',
    roleOrgImplication: '经理和流程所有者是采用系统的一部分，不是上线后的沟通对象。',
    nextAction: '在下一份访谈提纲中加入指标、激励、经理示范和流程修改权四个问题。',
    evidence: [{ sourceId: 'microsoft-worklab', title: '2026 Work Trend Index Annual Report', publisher: 'Microsoft WorkLab', url: 'https://www.microsoft.com/en-us/worklab/work-trend-index/agents-human-agency-and-the-opportunity-for-every-organization', publishedAt: '2026-05-05T00:00:00.000Z', level: 'single_source' }],
    riskLevel: 'medium', changeWindow: 'evergreen', factType: 'research_finding',
    verificationNotes: '报告样本、统计关联而非因果的边界已保留；销售问题为编辑转化。',
  }),
  defineCandidate({
    id: 'ST-017', slug: 'vendor-case-claim-check', seedCategory: 'enterprise_sales_method',
    title: '厂商客户案例要拆成事实、客户自述和待复核效果',
    summary: 'OpenAI 8 月 20 日发布 Stampli 案例，称其使用 Codex 与 ChatGPT Work 压缩发布制作周期；该效果来自厂商案例而非独立评估。',
    kind: 'method', domains: ['enterprise_sales', 'ai_technology'], topicSlugs: ['agent-business-model'],
    tags: ['客户案例', '企业自述', '证据'], toolIds: ['company-role-research', 'value-hypothesis-one-pager'], publishedAt: '2026-08-20T00:00:00.000Z', freshness: 'current',
    whyItMatters: '案例能帮助提出假设，但如果隐藏基线、样本和投入，就容易被误用为客户承诺。',
    salesImplication: '复述案例时标明发布方、客户、时间、范围、指标口径和未披露条件。',
    roleOrgImplication: '市场、销售与解决方案需要共用证据标注规则，避免夸大。',
    nextAction: '选一份厂商案例，用“已知事实、企业自述、未知条件、客户需验证”四栏重写。',
    evidence: [{ sourceId: 'openai-news-rss', title: 'Stampli cuts launch hours by 68% using ChatGPT Work', publisher: 'OpenAI', url: 'https://openai.com/index/stampli', publishedAt: '2026-08-20T00:00:00.000Z', level: 'official' }],
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'company_claim',
    verificationNotes: '标题、日期和 68% 主张由 OpenAI 官方 RSS 核验；明确未作独立效果确认。',
  }),
  defineCandidate({
    id: 'ST-018', slug: 'security-trust-discovery-questions', seedCategory: 'enterprise_sales_method',
    title: '企业 AI 信任发现要从口号拆到可验证控制',
    summary: 'OpenAI 的数据保留主张、NIST 风险框架与欧盟 AI Act 都指向数据、透明度、监督、日志和责任的可验证问题。',
    kind: 'method', domains: ['enterprise_sales', 'ai_technology', 'role_org'], topicSlugs: ['ai-buying-committee', 'ai-trust-governance'],
    tags: ['信任', '安全发现', '透明度'], toolIds: ['discovery-interview', 'stakeholder-adoption-risk'], publishedAt: '2026-08-19T19:00:00.000Z', freshness: 'current',
    whyItMatters: '“安全合规”不是一个复选框，不同客户对数据、模型、日志与监督有不同责任。',
    salesImplication: '把抽象担忧拆成控制、证据、负责人、例外和事故处理。',
    roleOrgImplication: '销售负责发现和协调，法律、安全与客户负责人负责正式判断。',
    nextAction: '用干系人风险清单写出五个控制问题及对应证据拥有者。',
    evidence: [
      { sourceId: 'openai-news-rss', title: 'Offering Zero Data Retention for frontier models', publisher: 'OpenAI', url: 'https://openai.com/index/offering-zero-data-retention-for-frontier-models', publishedAt: '2026-08-19T19:00:00.000Z', level: 'official' },
      { sourceId: 'nist-ai-rmf', title: 'AI Risk Management Framework', publisher: 'NIST', url: 'https://www.nist.gov/itl/ai-risk-management-framework', publishedAt: '2026-04-07T00:00:00.000Z', level: 'official', dateBasis: 'last_updated' },
      { sourceId: 'eu-ai-act', title: 'AI Act', publisher: 'European Commission', url: 'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai', publishedAt: '2026-08-03T00:00:00.000Z', level: 'official', dateBasis: 'last_updated' },
    ],
    riskLevel: 'high', changeWindow: 'within_30_days', factType: 'editorial_inference',
    verificationNotes: '仅提供发现问题框架，不构成安全或法律结论。',
  }),
  defineCandidate({
    id: 'ST-019', slug: 'applied-ai-architect-role', seedCategory: 'ai_role_change',
    title: 'Applied AI Architect 连接模型能力与客户生产环境',
    summary: 'Anthropic 招聘页在 8 月 23 日可见多地 Applied AI Architect 岗位，覆盖商业、行业、合作伙伴、企业技术与公共部门。',
    kind: 'role', domains: ['role_org', 'ai_technology', 'enterprise_sales'], topicSlugs: ['ai-commercial-role-map'],
    tags: ['Applied AI Architect', '售前', '解决方案'], toolIds: ['company-role-research', 'role-gap-analysis'], publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '岗位名称显示 AI 商业团队需要能把模型、数据、架构和客户约束连接起来的人。',
    salesImplication: '传统销售可强调复杂发现和协调能力，但需补足技术边界、评估与部署知识。',
    roleOrgImplication: 'Applied AI 与销售、工程和客户成功之间的接口需要清楚定义。',
    nextAction: '选择一个在招岗位，把前三项岗位结果映射到自己的证据与差距。',
    evidence: [{ sourceId: 'anthropic-careers', title: 'Anthropic Careers — Applied AI open roles', publisher: 'Anthropic', url: 'https://www.anthropic.com/careers/jobs', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', dateBasis: 'observed' }],
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '岗位列表为当日观察；岗位可能随时变化，能力结论为对多岗位名称的编辑归纳。',
  }),
  defineCandidate({
    id: 'ST-020', slug: 'forward-deployed-engineer-role', seedCategory: 'ai_role_change',
    title: 'Forward Deployed Engineer 把实施前移到客户现场',
    summary: 'Anthropic 招聘页在 8 月 23 日列出多个地区的 Forward Deployed Engineer 岗位，与 Applied AI 团队并列。',
    kind: 'role', domains: ['role_org', 'ai_technology', 'enterprise_sales'], topicSlugs: ['ai-commercial-role-map', 'ai-poc-scale'],
    tags: ['FDE', '客户实施', '共创'], toolIds: ['company-role-research', 'transition-evidence'], publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: 'AI 产品价值往往需要在客户流程、数据和系统中共同实现，售前与交付边界因而更靠近。',
    salesImplication: '销售需要更早确认实施资源、成功标准和客户工程配合。',
    roleOrgImplication: 'FDE 不等同于传统驻场开发；具体职责应以岗位原文和公司组织为准。',
    nextAction: '用岗位差距工具比较 FDE、解决方案架构师和传统售前三类结果。',
    evidence: [{ sourceId: 'anthropic-careers', title: 'Anthropic Careers — Forward Deployed Engineer', publisher: 'Anthropic', url: 'https://www.anthropic.com/careers/jobs', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', dateBasis: 'observed' }],
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '岗位存在性已核验；职责解释保持为编辑判断，需逐一打开岗位原文确认。',
  }),
  defineCandidate({
    id: 'ST-021', slug: 'technical-deployment-lead-role', seedCategory: 'ai_role_change',
    title: 'Technical Deployment Lead 负责把试点变成可运营部署',
    summary: 'Anthropic 招聘页在 8 月 23 日列出美国和英国的 Technical Deployment Lead 岗位。',
    kind: 'role', domains: ['role_org', 'ai_technology', 'enterprise_sales'], topicSlugs: ['ai-commercial-role-map', 'workflow-adoption'],
    tags: ['部署负责人', '运营', '采用'], toolIds: ['role-gap-analysis', 'poc-success-canvas'], publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '从 POC 到上线需要有人持续协调技术、风险、业务使用和交接。',
    salesImplication: '签约前应明确部署负责人、客户侧责任、运营指标和退出路径。',
    roleOrgImplication: '该角色体现交付、客户成功和技术实施正在形成新的组合。',
    nextAction: '为一个虚构项目写出部署负责人在启动、试点、扩展和运营四阶段的结果。',
    evidence: [{ sourceId: 'anthropic-careers', title: 'Anthropic Careers — Technical Deployment Lead', publisher: 'Anthropic', url: 'https://www.anthropic.com/careers/jobs', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', dateBasis: 'observed' }],
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '岗位名称和地区来自当日招聘页，职责组合是面向目标用户的编辑解释。',
  }),
  defineCandidate({
    id: 'ST-022', slug: 'presales-program-lead-role', seedCategory: 'ai_role_change',
    title: 'Pre-Sales Program Lead 强调售前方法与规模化机制',
    summary: 'Anthropic 招聘页在 8 月 23 日列出 Pre-Sales Program Lead, Forward Deployed Engineering 岗位。',
    kind: 'role', domains: ['role_org', 'enterprise_sales', 'ai_technology'], topicSlugs: ['ai-commercial-role-map'],
    tags: ['售前项目', 'FDE', '方法规模化'], toolIds: ['company-role-research', 'transition-evidence'], publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '当客户共创增多，售前不只做单个方案，还要建设重复使用的流程、标准和反馈闭环。',
    salesImplication: '有大项目方法、跨团队机制和复盘经验的销售可以形成可迁移证据。',
    roleOrgImplication: '售前项目管理与技术交付之间可能出现专门的运营角色。',
    nextAction: '把一次复杂售前经历改写成“建立了什么可复用机制”，而不只写成交结果。',
    evidence: [{ sourceId: 'anthropic-careers', title: 'Anthropic Careers — Pre-Sales Program Lead, Forward Deployed Engineering', publisher: 'Anthropic', url: 'https://www.anthropic.com/careers/jobs', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', dateBasis: 'observed' }],
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '岗位名称已核验；没有推断岗位数量趋势或跨公司普遍性。',
  }),
  defineCandidate({
    id: 'ST-023', slug: 'ai-fluency-education-lead-role', seedCategory: 'ai_role_change',
    title: 'AI Fluency Education Lead 把采用能力变成专门岗位',
    summary: 'Anthropic 招聘页在 8 月 23 日列出 AI Fluency Education Lead，并同时列出教育内容、课程和工程岗位。',
    kind: 'role', domains: ['role_org', 'ai_technology'], topicSlugs: ['ai-commercial-role-map', 'workflow-adoption'],
    tags: ['AI素养', '赋能', '采用'], toolIds: ['role-gap-analysis', 'transition-evidence'], publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '组织采用不只是购买许可，还需要把安全使用、判断和工作方法教给不同角色。',
    salesImplication: '销售可以把培训与采用指标纳入方案，但不能把一次培训等同于行为改变。',
    roleOrgImplication: '内容、教育、技术和组织变革能力开始在 AI 素养岗位交汇。',
    nextAction: '设计一份面向销售团队的 30 分钟 AI 素养练习，包含判断和复核而非只讲功能。',
    evidence: [{ sourceId: 'anthropic-careers', title: 'Anthropic Careers — AI Fluency Education Lead', publisher: 'Anthropic', url: 'https://www.anthropic.com/careers/jobs', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', dateBasis: 'observed' }],
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '只以当日在招岗位说明角色存在，不声称它已成为行业标准职位。',
  }),
  defineCandidate({
    id: 'ST-024', slug: 'agentops-gtm-systems-role', seedCategory: 'ai_role_change',
    title: 'AgentOps 与 GTM Systems 开始在商业系统岗位交叉',
    summary: 'Anthropic 招聘页在 8 月 23 日列出 DevOps / AgentOps Engineer, GTM Systems 与 Program Manager, GTM Systems 等岗位。',
    kind: 'role', domains: ['role_org', 'ai_technology', 'enterprise_sales'], topicSlugs: ['ai-commercial-role-map', 'agent-business-model'],
    tags: ['AgentOps', 'GTM Systems', '商业运营'], toolIds: ['company-role-research', 'role-gap-analysis'], publishedAt: '2026-08-23T00:00:00.000Z', freshness: 'current',
    whyItMatters: '商业团队的自动化正在需要可靠性、权限、流程和系统运营，而不只是购买销售工具。',
    salesImplication: '销售运营经验可以迁移，但需补足代理可观测性、权限和故障治理。',
    roleOrgImplication: 'GTM 系统可能成为销售运营、工程与 AgentOps 的共同责任面。',
    nextAction: '列出一个销售流程中代理的触发、权限、日志、失败和人工接管五项要求。',
    evidence: [{ sourceId: 'anthropic-careers', title: 'Anthropic Careers — DevOps / AgentOps Engineer, GTM Systems', publisher: 'Anthropic', url: 'https://www.anthropic.com/careers/jobs', publishedAt: '2026-08-23T00:00:00.000Z', level: 'official', dateBasis: 'observed' }],
    riskLevel: 'medium', changeWindow: 'within_90_days', factType: 'editorial_inference',
    verificationNotes: '岗位名称已核验；跨职能趋势为单家公司岗位样本上的谨慎推断。',
  }),
  defineCandidate({
    id: 'ST-025', slug: 'eu-ai-act-august-2026', seedCategory: 'org_adoption',
    title: '欧盟 AI Act 于 2026 年 8 月进入更完整适用阶段',
    summary: '欧盟委员会页面显示 AI Act 于 2026 年 8 月 2 日开始适用，并同步进入治理、执法和透明度要求的新阶段；部分高风险规则有更晚过渡期。',
    kind: 'update', domains: ['role_org', 'ai_technology', 'enterprise_sales'], topicSlugs: ['ai-trust-governance', 'ai-buying-committee'],
    tags: ['EU AI Act', '透明度', '治理'], toolIds: ['stakeholder-adoption-risk', 'ai-maturity-scan'], publishedAt: '2026-08-03T00:00:00.000Z', freshness: 'breaking',
    whyItMatters: '面向欧洲客户的产品、部署者和采购方需要区分已适用义务、未来高风险时间线和具体角色。',
    salesImplication: '不能把“AI Act 合规”当通用承诺；应让客户法律团队确认角色、用途、地域和时间线。',
    roleOrgImplication: '产品、法务、安全和内容团队需要共同维护透明度与监督流程。',
    nextAction: '为一个虚构欧洲场景写出提供者、部署者、用途、风险类别和待法律确认问题。',
    evidence: [{ sourceId: 'eu-ai-act', title: 'AI Act', publisher: 'European Commission', url: 'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai', publishedAt: '2026-08-03T00:00:00.000Z', level: 'official', dateBasis: 'last_updated' }],
    riskLevel: 'high', changeWindow: 'within_30_days', factType: 'official_fact',
    verificationNotes: '页面最后更新为 8 月 3 日并列出适用时间线；本条不提供法律建议，发布前需法律复核。',
  }),
  defineCandidate({
    id: 'ST-026', slug: 'human-agency-needs-system-redesign', seedCategory: 'org_adoption',
    title: '个人会用 AI，不等于组织已经准备好',
    summary: 'Microsoft 2026 Work Trend Index 基于 20,000 名 AI 使用者调查，提出个人能力与组织文化、经理支持、治理和人才实践之间存在准备度错位。',
    kind: 'explainer', domains: ['role_org', 'enterprise_sales'], topicSlugs: ['workflow-adoption'],
    tags: ['组织准备度', '经理支持', '工作重构'], toolIds: ['ai-maturity-scan', 'stakeholder-adoption-risk'], publishedAt: '2026-05-05T00:00:00.000Z', freshness: 'evergreen',
    whyItMatters: '用户个人的高频使用可能被旧指标、权限和经理行为阻塞，形成“试用很多、价值很少”。',
    salesImplication: '采用方案要评估组织条件，不把许可证激活率当作业务影响。',
    roleOrgImplication: '领导、经理、IT、安全和员工分别承担方向、支持、控制与判断责任。',
    nextAction: '用成熟度扫描分别给个人能力和组织支持列证据，不用一个总分掩盖错位。',
    evidence: [{ sourceId: 'microsoft-worklab', title: '2026 Work Trend Index Annual Report', publisher: 'Microsoft WorkLab', url: 'https://www.microsoft.com/en-us/worklab/work-trend-index/agents-human-agency-and-the-opportunity-for-every-organization', publishedAt: '2026-05-05T00:00:00.000Z', level: 'single_source' }],
    riskLevel: 'medium', changeWindow: 'evergreen', factType: 'research_finding',
    verificationNotes: '保留 10 个市场、自报调查与相关而非因果的研究边界。',
  }),
  defineCandidate({
    id: 'ST-027', slug: 'agent-lifecycle-needs-owner', seedCategory: 'org_adoption',
    title: '规模化代理需要身份、权限、评估和下线责任人',
    summary: 'Google Gemini Enterprise 官方材料把代理身份、网关、模拟和可观测性列为统一控制面能力。',
    kind: 'method', domains: ['role_org', 'ai_technology'], topicSlugs: ['ai-trust-governance', 'workflow-adoption'],
    tags: ['代理生命周期', '责任人', '控制面'], toolIds: ['stakeholder-adoption-risk'], publishedAt: '2026-04-22T00:00:00.000Z', freshness: 'evergreen',
    whyItMatters: '没有责任人的代理会积累权限、知识和运行风险，且难以安全撤回。',
    salesImplication: '方案应明确谁批准代理、谁看日志、谁改工作流、谁能暂停和下线。',
    roleOrgImplication: '代理应像账号和应用一样拥有可追溯生命周期，而非一次性项目产物。',
    nextAction: '用风险清单为一个代理指定业务、技术、安全和下线四类责任人。',
    evidence: [{ sourceId: 'google-cloud-ai-blog', title: 'The new Gemini Enterprise: one platform for agent development, orchestration, and governance', publisher: 'Google Cloud', url: 'https://cloud.google.com/blog/products/ai-machine-learning/the-new-gemini-enterprise-one-platform-for-agent-development', publishedAt: '2026-04-22T00:00:00.000Z', level: 'official' }],
    riskLevel: 'medium', changeWindow: 'evergreen', factType: 'editorial_inference',
    verificationNotes: '产品能力是厂商自述；责任模型为基于控制面的编辑建议。',
  }),
  defineCandidate({
    id: 'ST-028', slug: 'architecture-contract-as-org-memory', seedCategory: 'org_adoption',
    title: '把组织标准编码进架构合同，减少代理输出漂移',
    summary: 'AWS ADOP 参考架构提出用架构合同、规则和 CI/CD 约束不同 AI 编码工具，并让工程师审核生成产物。',
    kind: 'case', domains: ['role_org', 'ai_technology', 'enterprise_sales'], topicSlugs: ['workflow-adoption', 'ai-poc-scale'],
    tags: ['架构合同', '组织记忆', '一致性'], toolIds: ['ai-maturity-scan', 'poc-success-canvas'], publishedAt: '2026-08-21T17:06:17.000Z', freshness: 'breaking',
    whyItMatters: '如果标准只在专家脑中，不同团队和工具会重复做出不一致的架构决定。',
    salesImplication: '价值可以包括减少重复评审和提高一致性，但仍需客户用实际产物验证。',
    roleOrgImplication: '专家从逐项执行转向维护可复用标准、审核例外和改进合同。',
    nextAction: '选择一个重复流程，写出三条不可违反的标准和一个人工例外门。',
    evidence: [{ sourceId: 'aws-ai-blog-rss', title: 'Agentic Data Operations Platform (ADOP): Data engineering into hours', publisher: 'Amazon Web Services', url: 'https://aws.amazon.com/blogs/machine-learning/agentic-data-operations-platform-adop-data-engineering-into-hours/', publishedAt: '2026-08-21T17:06:17.000Z', level: 'official' }],
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'company_claim',
    verificationNotes: '架构模式来自 AWS 官方文章，效果仍需在客户环境独立验证。',
  }),
  defineCandidate({
    id: 'ST-029', slug: 'enterprise-ai-from-assistance-to-execution', seedCategory: 'org_adoption',
    title: '企业 AI 采用焦点正在从辅助转向执行与运营',
    originalTitle: 'From assistance to execution: How enterprises put AI to work',
    summary: 'OpenAI 8 月 12 日发布企业采用研究，称企业正在把 ChatGPT 与 Codex 用于更复杂的代理式工作，并强调领先组织的采用差距。',
    kind: 'update', domains: ['role_org', 'ai_technology', 'enterprise_sales'], topicSlugs: ['workflow-adoption', 'agent-business-model'],
    tags: ['企业采用', '执行', '运营'], toolIds: ['ai-maturity-scan', 'value-hypothesis-one-pager'], publishedAt: '2026-08-12T06:00:00.000Z', freshness: 'current',
    whyItMatters: '从个人辅助到流程执行会改变权限、评估、支持和业务责任。',
    salesImplication: '机会判断要问客户想增强个人还是重构流程，两者的采购与实施条件不同。',
    roleOrgImplication: '组织需要从工具培训转向工作设计、代理运营和持续学习。',
    nextAction: '把一个目标场景标为辅助、协作或执行，并写出升级到下一层所需的控制。',
    evidence: [{ sourceId: 'openai-news-rss', title: 'From assistance to execution: How enterprises put AI to work', publisher: 'OpenAI', url: 'https://openai.com/index/how-enterprises-put-ai-to-work', publishedAt: '2026-08-12T06:00:00.000Z', level: 'official' }],
    riskLevel: 'medium', changeWindow: 'within_30_days', factType: 'company_claim',
    verificationNotes: '标题、日期与摘要从 OpenAI 官方 RSS 核验；研究结论按厂商研究标识。',
  }),
  defineCandidate({
    id: 'ST-030', slug: 'skills-change-ai-work', seedCategory: 'org_adoption',
    title: 'AI 转型首先表现为岗位技能组合持续变化',
    originalTitle: 'Work Change Report: AI is Coming to Work',
    summary: 'LinkedIn Economic Graph 2025 报告预测，到 2030 年多数岗位使用的技能中约 70% 会发生变化，并披露成员新增技能速度上升。',
    kind: 'explainer', domains: ['role_org', 'enterprise_sales'], topicSlugs: ['ai-commercial-role-map', 'workflow-adoption'],
    tags: ['技能变化', '转岗', '组织学习'], toolIds: ['transition-evidence', 'role-gap-analysis'], publishedAt: '2025-01-01T00:00:00.000Z', freshness: 'evergreen',
    whyItMatters: '岗位名称未变时，工作结果、工具和协作方式也可能先改变。',
    salesImplication: '转岗准备应持续对照岗位原页和真实任务，而不是一次性背诵技能清单。',
    roleOrgImplication: '组织需要按工作结果更新学习与人才实践，不把一次培训当作转型完成。',
    nextAction: '选择一个目标岗位，把技能分成保留、重组和新增三类并各找一条证据。',
    evidence: [{ sourceId: 'linkedin-economic-graph', title: 'Work Change Report: AI is Coming to Work', publisher: 'LinkedIn Economic Graph', url: 'https://economicgraph.linkedin.com/research/work-change-report', publishedAt: '2025-01-01T00:00:00.000Z', level: 'single_source' }],
    riskLevel: 'medium', changeWindow: 'evergreen', factType: 'research_finding',
    verificationNotes: '保留 LinkedIn 平台数据与预测属性，不把 70% 解释为每个岗位都必然相同。',
  }),
] as const satisfies readonly SeedCandidate[];
